<?php /* @var $this Aoe_Static_Block_Beforebodyend */?>
<script type="text/javascript">
    <?php // TODO: rewrite recently viewed products feature to be handled client side using localStorage. In this case more data needs to be added here and stored in the client ?>
    jQuery(document).ready(function() {
        Aoe_Static.init(
            '<?php echo $this->getAjaxCallUrl() ?>',
            '<?php echo $this->getFullActionName() ?>',
            <?php echo $this->getCurrentStoreId() ?>,
            <?php echo $this->getCurrentWebsiteId() ?>,
            <?php echo $this->getCurrentProductId() ?>
        );
    });
</script>
